#!/usr/bin/env tsx
/**
 * Devnet setup script:
 *   1. Airdrop SOL to facilitator keypair
 *   2. Create USDC-like test token (stake token)
 *   3. Mint test tokens to facilitator
 *   4. Initialize the x402-network program
 *
 * Usage: npx tsx scripts/setup-devnet.ts
 */

import {
  Connection,
  Keypair,
  PublicKey,
  LAMPORTS_PER_SOL,
} from "@solana/web3.js";
import {
  createMint,
  getOrCreateAssociatedTokenAccount,
  mintTo,
  TOKEN_PROGRAM_ID,
} from "@solana/spl-token";
import { readFileSync, writeFileSync, existsSync } from "fs";

const RPC = process.env.HELIUS_RPC_URL ?? "https://api.devnet.solana.com";
const connection = new Connection(RPC, "confirmed");

async function main() {
  console.log("🚀 x402-network devnet setup");
  console.log("RPC:", RPC);

  // Load or generate facilitator keypair
  let facilitator: Keypair;
  if (existsSync("./facilitator.json")) {
    const raw = JSON.parse(readFileSync("./facilitator.json", "utf-8"));
    facilitator = Keypair.fromSecretKey(new Uint8Array(raw));
    console.log("Loaded existing keypair:", facilitator.publicKey.toBase58());
  } else {
    facilitator = Keypair.generate();
    writeFileSync("./facilitator.json", JSON.stringify(Array.from(facilitator.secretKey)));
    console.log("Generated new keypair:", facilitator.publicKey.toBase58());
  }

  const balance = await connection.getBalance(facilitator.publicKey);
  console.log("   Balance:", balance / LAMPORTS_PER_SOL, "SOL");

  // 2. Create stake token mint
  console.log("\n2. Creating X402 stake token...");
  const mint = await createMint(
    connection,
    facilitator,
    facilitator.publicKey, // mint authority
    facilitator.publicKey, // freeze authority
    6 // decimals (same as USDC)
  );
  console.log("   Mint:", mint.toBase58());

  // 3. Create ATA and mint tokens
  console.log("\n3. Minting 10,000 X402 tokens to facilitator...");
  const ata = await getOrCreateAssociatedTokenAccount(
    connection,
    facilitator,
    mint,
    facilitator.publicKey
  );
  await mintTo(
    connection,
    facilitator,
    mint,
    ata.address,
    facilitator,
    10_000 * 1_000_000 // 10,000 tokens
  );
  console.log("   ATA:", ata.address.toBase58());

  // Write .env updates
  const envAdditions = `
# Auto-generated by setup-devnet.ts
STAKE_MINT=${mint.toBase58()}
FACILITATOR_KEYPAIR_PATH=./facilitator.json
`;
  console.log("\n✅ Setup complete! Add to your .env:");
  console.log(envAdditions);
  writeFileSync(".env.devnet-generated", envAdditions.trim());

  console.log("\nNext steps:");
  console.log("  1. anchor build && anchor deploy --provider.cluster devnet");
  console.log("  2. Update NETWORK_PROGRAM_ID in .env with the deployed program ID");
  console.log("  3. Run: npx tsx scripts/initialize-network.ts");
  console.log("  4. Run: npm run dev:facilitator");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
